# Generated by Django 3.0.3 on 2020-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blopper',
            name='liked_blops',
            field=models.ManyToManyField(to='main_app.Blop'),
        ),
        migrations.AlterField(
            model_name='blop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blop',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
