# Generated by Django 3.0.3 on 2020-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200207_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_media'),
        ),
    ]
