# Generated by Django 3.0.2 on 2020-02-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200207_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blop',
            options={'ordering': ['-likes']},
        ),
        migrations.AlterField(
            model_name='blop',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blop',
            name='video',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
