# Generated by Django 3.0.3 on 2020-02-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200207_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blop',
            name='article',
            field=models.URLField(blank=True),
        ),
    ]
