# Generated by Django 3.0.3 on 2020-02-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200208_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blop',
            name='article',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
