# Generated by Django 3.0.2 on 2020-02-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200208_0206'),
        ('main_app', '0006_auto_20200208_0130'),
    ]

    operations = [
    ]
