# Generated by Django 3.0.2 on 2020-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20200208_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blop',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
