# Generated by Django 3.0.2 on 2020-02-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200210_0333'),
        ('main_app', '0006_auto_20200208_0128'),
    ]

    operations = [
    ]
